# Generated by Django 3.1 on 2020-09-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HERO_NAME', models.CharField(max_length=50)),
                ('HEROINE_NAME', models.CharField(max_length=50)),
                ('MOVIE_NAME', models.CharField(max_length=50)),
                ('RELEASE_DATE', models.DateField()),
                ('MOVIE_DURATION', models.FloatField()),
                ('NO_OF_SONGS', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Movie_Info',
                'verbose_name_plural': 'Movie_Infos',
            },
        ),
    ]
